server:
  port: 8082

spring:
  application.name: vinsguru-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scb_microservice_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: paymentProcessor
    stream:
      bindings:
        paymentProcessor-in-0:
          destination: order-event
        paymentProcessor-out-0:
          destination: payment-event