server:
  port: 8081

spring.cloud.function:
  definition: numberProducer

spring.cloud.stream:
  kafka:
    binder:
      brokers:
        - localhost:9092
  bindings:
    numberProducer-out-0:
      destination: numbers
      group: number-group